# Use the official PostgreSQL image as the base image
FROM postgres:16

# Set the PostgreSQL user and database
ENV POSTGRES_USER administrator
ENV POSTGRES_DB tournaments_db

# Set the PostgreSQL password
ENV POSTGRES_PASSWORD E#Lyvsyf4dtnCkV^r9PEn4